# Generated by Django 4.2.11 on 2024-04-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredientinrecipe_recipe_recipetag_recipe_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='amout',
            new_name='amount',
        ),
    ]
