# Generated by Django 4.2.11 on 2024-04-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_subscribe_shoppingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
