# Generated by Django 4.2.11 on 2024-06-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options_alter_subscribe_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/images/', verbose_name='Изображение'),
        ),
    ]
